### ISSUE TITLE
Duplicate thingCategory ExoSuits

### ISSUE THREAD

**Issue by mdrain18** [emipa606/RimworldSpartanFoundry#1]
Yolo,
I'm getting this error on load of the mod. Funny thing is some of my items also get this same error and I can not for the life of me figure out why its doing that. 

When you figure this out, please let me know what you changed :)

Config error in SF_PoweredAssaultArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_PoweredAssaultArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_EngineerPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_EngineerPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ExplorerPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ExplorerPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_GrenadierPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_GrenadierPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_CommandoArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_CommandoArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_HazardOperationsArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_HazardOperationsArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_DiplomatPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_DiplomatPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_DefenderPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_DefenderPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ScoutPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ScoutPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_SamuraiPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_SamuraiPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ShockTrooperArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ShockTrooperArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ReconPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Config error in SF_ReconPowerArmor: has duplicate thingCategory ExoSuits. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by emipa606** [comment]
Does not happen with only this mod loaded so you may have a mod-conflict.
Try removing mods until you find what mods is causing it.
