### ISSUE TITLE
Save our Ship 2 compatibility?

### ISSUE THREAD

**Issue by Deathgow** [emipa606/RimworldSpartanFoundry#3]
so currently all the armors have 75% decompression resistance but the helmets have nothing, they usually have 25% decompression resistance and 100% hypoxia resistance as per vanilla power armor helmets, also worth to note that the combined cold resistance of the armor should be more than -100c in order to survive the vacuum of space.
I would love to use these armors in space with SoS2, thanks a lot for checking this out

**Comment by emipa606** [comment]
Should be fixed now, thanks for reporting
